"""
engine/engine.py — command-line entry-point for the surajk plugin AI engine.

Usage
-----
    python engine.py --image <path_to_image> --output <output_directory>

Outputs
-------
<output_dir>/<image_stem>.obj   — Wavefront OBJ mesh
<output_dir>/<image_stem>.mtl   — Material library (basic diffuse)

The geometry is generated by mesh_generator.generate().
Swap in real model weights in engine/models/ and update
mesh_generator.generate() to use them without changing this file.
"""

from __future__ import annotations

import argparse
import os
import sys
import time
from pathlib import Path

# Ensure the engine directory is on sys.path so that relative imports work
# when this script is called via the batch launcher.
sys.path.insert(0, str(Path(__file__).parent))

from mesh_generator import generate  # noqa: E402 (after sys.path manipulation)


# ---------------------------------------------------------------------------
# OBJ / MTL writers
# ---------------------------------------------------------------------------

def write_obj(
    output_dir: Path,
    stem: str,
    vertices: list,
    faces: list,
) -> Path:
    """
    Write a Wavefront .obj file and companion .mtl file.

    Returns the path to the .obj file.
    """
    obj_path = output_dir / f"{stem}.obj"
    mtl_path = output_dir / f"{stem}.mtl"

    # Write MTL first so the OBJ can reference it.
    _write_mtl(mtl_path, stem)

    with obj_path.open("w", encoding="utf-8") as fh:
        fh.write(f"# Generated by surajk plugin engine\n")
        fh.write(f"# Source image stem: {stem}\n\n")
        fh.write(f"mtllib {stem}.mtl\n")
        fh.write(f"o {stem}\n\n")
        fh.write("usemtl default_material\n\n")

        # Vertices
        for x, y, z in vertices:
            fh.write(f"v {x:.6f} {y:.6f} {z:.6f}\n")

        fh.write("\n# Faces (1-based indices)\n")
        for i, j, k in faces:
            fh.write(f"f {i+1} {j+1} {k+1}\n")

    return obj_path


def _write_mtl(mtl_path: Path, stem: str) -> None:
    """Write a minimal MTL file with a single diffuse material."""
    with mtl_path.open("w", encoding="utf-8") as fh:
        fh.write(f"# Generated by surajk plugin engine\n")
        fh.write(f"newmtl default_material\n")
        fh.write(f"Ka 0.200 0.200 0.200\n")   # ambient
        fh.write(f"Kd 0.800 0.600 0.400\n")   # diffuse (warm wood tone)
        fh.write(f"Ks 0.100 0.100 0.100\n")   # specular
        fh.write(f"Ns 10.0\n")                 # shininess
        fh.write(f"d 1.0\n")                   # opacity


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> int:
    parser = argparse.ArgumentParser(
        description="surajk plugin — image-to-3D mesh engine"
    )
    parser.add_argument(
        "--image", "-i",
        required=True,
        help="Absolute path to the input image (JPG or PNG).",
    )
    parser.add_argument(
        "--output", "-o",
        required=True,
        help="Output directory for the generated .obj / .mtl files.",
    )
    args = parser.parse_args()

    image_path = Path(args.image)
    output_dir = Path(args.output)

    # -----------------------------------------------------------------------
    # Validate input image
    # -----------------------------------------------------------------------
    if not image_path.exists():
        print(f"[ERROR] Image not found: {image_path}", file=sys.stderr)
        return 1
    if image_path.suffix.lower() not in {".jpg", ".jpeg", ".png"}:
        print(
            f"[ERROR] Unsupported image format '{image_path.suffix}'. "
            "Use JPG or PNG.",
            file=sys.stderr,
        )
        return 1

    # -----------------------------------------------------------------------
    # Ensure output directory exists
    # -----------------------------------------------------------------------
    try:
        output_dir.mkdir(parents=True, exist_ok=True)
    except OSError as exc:
        print(f"[ERROR] Cannot create output directory: {exc}", file=sys.stderr)
        return 1

    # -----------------------------------------------------------------------
    # Generate mesh
    # -----------------------------------------------------------------------
    stem = image_path.stem
    print(f"[INFO]  Processing image : {image_path}")
    print(f"[INFO]  Output directory : {output_dir}")

    t0 = time.time()
    try:
        vertices, faces = generate(str(image_path))
    except (FileNotFoundError, ValueError, OSError, RuntimeError) as exc:
        print(f"[ERROR] Mesh generation failed: {exc}", file=sys.stderr)
        return 1

    elapsed = time.time() - t0
    print(f"[INFO]  Mesh generated   : {len(vertices)} verts, "
          f"{len(faces)} faces  ({elapsed:.2f}s)")

    # -----------------------------------------------------------------------
    # Write OBJ + MTL
    # -----------------------------------------------------------------------
    try:
        obj_path = write_obj(output_dir, stem, vertices, faces)
    except OSError as exc:
        print(f"[ERROR] Failed to write OBJ: {exc}", file=sys.stderr)
        return 1

    print(f"[OK]    OBJ written      : {obj_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
